on:
  push:
    branches: [ master ]
name: Build and Publish Javadocs And Reports
jobs:
  DoIt:
    name: DoIt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Build with Gradle
        run: ./scripts/buildMe.sh
      - name: Upload Reports
        shell: bash
        env:
          SITE_USER: ${{ secrets.USER }}
          SITE_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          SITE_HOST: ${{ secrets.SERVER }}
        run: ./scripts/upload.sh
